apiVersion: apps/v1
kind: Deployment
metadata:
  name: talosctl
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: talosctl
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: talosctl
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: talosctl
      {{- if not .Values.talosctl.talosconfig }}
      automountServiceAccountToken: false
      {{- end }}
      containers:
        - name: talosctl
          image: "{{ .Values.talosctl.image.repository }}:{{ .Values.talosctl.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - infinity
          {{- if .Values.talosctl.talosconfig }}
          env:
            - name: TALOSCONFIG
              value: /talos/config
          volumeMounts:
            - name: talosconfig
              mountPath: /talos
              readOnly: true
          {{- else }}
          volumeMounts:
            - name: talos-serviceaccount-token
              mountPath: /var/run/secrets/talos.dev
              readOnly: true
          {{- end }}
          resources:
            {{- toYaml .Values.talosctl.resources | nindent 12 }}
      volumes:
        {{- if .Values.talosctl.talosconfig }}
        - name: talosconfig
          secret:
            secretName: talosconfig
        {{- else }}
        - name: talos-serviceaccount-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: talos
                  expirationSeconds: 3600
                  path: token
        {{- end }}
