apiVersion: v1
kind: ServiceAccount
metadata:
  name: talosctl
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: talosctl-talos-secrets
  namespace: {{ .Release.Namespace }}
spec:
  roles:
    - os:admin
