apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: talosconfig
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    config: {{ .Values.talosctl.talosconfig | required "talosctl.talosconfig is required" }}
  template:
    metadata:
      name: talosconfig
      namespace: {{ .Release.Namespace }}
