{{- if .Values.talosctl.talosconfig -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: talosconfig
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    config: {{ .Values.talosctl.talosconfig }}
  template:
    metadata:
      name: talosconfig
      namespace: {{ .Release.Namespace }}
{{- end }}
