{{- if and .Values.argocdMcpOidc.enabled .Values.argocdMcpOidc.clientSecretSealed -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.argocdMcpOidc.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    client-secret: {{ .Values.argocdMcpOidc.clientSecretSealed }}
  template:
    metadata:
      name: {{ .Values.argocdMcpOidc.secretName }}
      namespace: {{ .Release.Namespace }}
{{- end }}
