{{- if .Values.argocdMcpBearerAuth.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: argocd-mcp-server-security-policy
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: argocd-mcp-server
  apiKeyAuth:
    credentialRefs:
      - group: ""
        kind: Secret
        name: argocd-mcp-bearer-auth-secret
    extractFrom:
      - headers:
          - Authorization
    sanitize: true
{{- end }}
