 node-problem-detector:
   metrics:
     enabled: true
     serviceMonitor:
       enabled: true
     prometheusRule:
       enabled: true
       defaultRules:
         create: true

   resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 20m
        memory: 40Mi
