snapshot-controller:
  controller:
    revisionHistoryLimit: 0
    args:
      automaxprocs: true
      kube-api-qps: 15
      kube-api-burst: 30
    resources:
      requests:
        cpu: 10m
        memory: 60Mi
      limits:
        memory: 120Mi

    serviceMonitor:
      create: true

  webhook:
    enabled: false
