apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: ai-envoy-gateway
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway-private
      sectionName: ai-web
  http3: {}
  path:
    escapedSlashesAction: KeepUnchanged
  tls:
    minVersion: '1.2'
    ciphers:
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
  headers:
    lateResponseHeaders:
      set:
        - name: "strict-transport-security"
          value: "max-age=31536000; includeSubDomains"
        - name: "x-content-type-options"
          value: "nosniff"
  # AI Gateway specific values
  connection:
    bufferLimit: 50Mi
