apiVersion: v2
name: envoy-gateway
version: 1.0.41

dependencies:
  - name: gateway-helm
    version: 1.8.1
    repository: oci://docker.io/envoyproxy
  - name: gateway-addons-helm
    version: 1.8.2
    repository: oci://docker.io/envoyproxy
