gateway-helm:
  podDisruptionBudget:
    minAvailable: 1

  deployment:
    envoyGateway:
      resources:
        limits:
          memory: 256Mi
        requests:
          cpu: 50m
          memory: 128Mi
    replicas: 2

  config:
    envoyGateway:
      logging:
        level:
          default: warn
      extensionApis:
        enableBackend: true
      extensionManager:
        hooks:
          xdsTranslator:
            translation:
              listener:
                includeAll: true
              route:
                includeAll: true
              cluster:
                includeAll: true
              secret:
                includeAll: true
            post:
              - Translation
              - Cluster
              - Route
        service:
          fqdn:
            hostname: ai-gateway-controller.envoy-ai-gateway.svc.cluster.local
            port: 1063

aiTlsCertificate:
  domains:
    - "*.ai.feddema.dev"
defaultTlsCertificate:
  domains:
    - "feddema.dev"
    - "*.feddema.dev"
    - "*.mcp.feddema.dev"

httpRedirect:
  statusCode: 301

gateways:
  public:
    addresses:
      - 95.98.178.131
    serviceAddress: 192.168.102.30
    replicas: 3
    pdb:
      minAvailable: 2
    resources:
      requests:
        cpu: 150m
        memory: 300Mi
      limits:
        memory: 600Mi

  private:
    addresses:
      - 192.168.102.31
    serviceAddress: 192.168.102.31
    replicas: 3
    pdb:
      minAvailable: 2
    resources:
      requests:
        cpu: 150m
        memory: 300Mi
      limits:
        memory: 600Mi

gateway-addons-helm:
  dashboard:
    labels:
      grafana_dashboard: "1"
  grafana:
    enabled: false
  prometheus:
    enabled: false
  fluent-bit:
    enabled: false
  loki:
    enabled: false
  tempo:
    enabled: false
