{{- if .Values.auth.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-mcp-server-secret-init
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-mcp-server-secret-init
subjects:
  - kind: ServiceAccount
    name: argocd-mcp-server-secret-init
    namespace: {{ .Release.Namespace }}
{{- end }}
