apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "donetick.fullname" . }}-init-jwt-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
