apiVersion: v2
name: sealed-secrets
version: 1.0.27

dependencies:
  - name: sealed-secrets
    version: 2.18.3
    repository: https://bitnami-labs.github.io/sealed-secrets
  - name: sealed-secrets-web
    version: 3.2.1
    repository: oci://ghcr.io/bakito/helm-charts
