apiVersion: v2
name: sealed-secrets
version: 1.0.29

dependencies:
  - name: sealed-secrets
    version: 2.18.4
    repository: https://bitnami-labs.github.io/sealed-secrets
  - name: sealed-secrets-web
    version: 3.3.0
    repository: oci://ghcr.io/bakito/helm-charts
  - name: gatus-monitor
    repository: file://../../../templates/gatus-monitor
    version: 1.0.0
