gatus-monitor:
  appName: sealedsecrets
  publicEndpoints:
    - name: sealedsecrets
  privateEndpoints:
    - name: sealedsecrets

sealed-secrets:
  createController: true

  secretName: "sealed-secrets-key"
  keyrenewperiod: "0"

  fullnameOverride: "sealed-secrets-controller"

  podSecurityContext:
    enabled: true
    fsGroup: 65534

  containerSecurityContext:
    enabled: true
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1001

  revisionHistoryLimit: '0'
  resources:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      memory: 80Mi

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: false

  networkPolicy:
    enabled: false

  serviceAccount:
    create: true

  rbac:
    create: true
    pspEnabled: false

  metrics:
    serviceMonitor:
      enabled: true

    dashboards:
      create: true

route:
  publicKey:
    hostnames:
      - sealedsecrets.feddema.dev
    parentRefs:
      - name: envoy-gateway-private
        namespace: envoy-gateway
        sectionName: web-https
    matches:
      - path:
          type: PathPrefix
          value: /v1/cert.pem
  web:
    hostnames:
      - sealedsecrets.feddema.dev
    parentRefs:
      - name: envoy-gateway-public
        namespace: envoy-gateway
        sectionName: web-https
      - name: envoy-gateway-private
        namespace: envoy-gateway
        sectionName: web-https

sealed-secrets-web:
  fullnameOverride: sealed-secrets-web
  revisionHistoryLimit: 0
  disableLoadSecrets: true

  sealedSecrets:
    serviceName: sealed-secrets-controller

  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      memory: 100Mi

  nodeSelector:
    kubernetes.io/arch: amd64

