apiVersion: v2
name: grafana
version: 1.0.174

dependencies:
  - name: grafana
    version: 12.2.1
    repository: https://grafana-community.github.io/helm-charts
  - name: gatus-monitor
    repository: file://../../../templates/gatus-monitor
    version: 1.0.0
