metrics-server:
  replicas: 2
  revisionHistoryLimit: 0

  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 20m
      memory: 80Mi

  metrics:
    enabled: true

  serviceMonitor:
    enabled: true

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""

  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
