{
 "title": "Adguard",
 "tags": [ "adguard" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "AdGuard Home",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(adguard_running)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Protection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(adguard_protection_enabled)"
    }
   ]
  },
  {
   "title": "Processing TIme",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(adguard_avg_processing_time > 0)",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Number of queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(adguard_num_dns_queries)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(adguard_num_blocked_filtering)"
    }
   ]
  },
  {
   "title": "Percent of ads blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(adguard_num_blocked_filtering > 0) / sum(adguard_num_dns_queries > 0) * 100"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(domain) (adguard_top_queried_domains)",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(domain) (adguard_top_blocked_domains)",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "adguard_num_dns_queries > 0", "legendFormat": "{{ hostname }}" }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type) (adguard_query_types)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(type) (adguard_query_types)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top clients by source",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by(client) (adguard_top_clients)",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering > 0",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top clients",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(client) (adguard_top_clients)",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(adguard_num_blocked_filtering / adguard_num_dns_queries * 100) > 0",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(domain) (adguard_top_blocked_domains)",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (domain) (adguard_top_queried_domains)",
     "legendFormat": "{{ domain }}"
    }
   ]
  }
 ]
}