---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: kyverno
spec:
  encryptedData:
    GITHUB_TOKEN: AgAgBNqO6zQNulwljCdiF1D8TaEgGL9oheac2qOSNEMqSrLBVZq0OTGHGpW2/x3K+ZYucoi1MoNgnOp37A9nHv/Loa4c6Xcw3NG3Bx8BCuEGN2iCYMXhrXb52pV43yKi3TVINpFruXTNttn37+n6ETIjz2SZHigXCi6Szgl9ZggGUdQ0NBVufoKI1u40CimOXXwG+4EcwAh8jlDMnbxLEdOS48lZwY7160JMDNkBRv1W2Mqft3GH0GER7JidnI+dy4SHcdg0atkKO2r0tOoXdKN05e83tlkZVYu1eodC8Qkj4eZ5rKT6r1e5If9/9agcK6eq2kNDaK1aUZ01XZZ9GjevodJiVTWee9dtWvYxYO/JGcQX7OWXbPzt6Ve0bYohIyaUYhHtJ3RUWpkwqKhUUphKF/9NDSj3+HYSHPIZy4BUsynTsN49bOyuF6GHNz08zS6TYRe88LNowusZ3RuxZqT6DYl8J2egq2iq5/y/HZfpV5ezrFM9eFz+kUh+RQhUszN+X2AiTxPccP3eCM4KppgIDrEgy8prreLGNn/xv0i7lfoUIo2+FeNxjigZcDhTF2QhxnVlLF1HhhWdEOrIRvuF8lxTARp4UVgpaYCyqXq+TjCB6rQjGw/ayeUpd9tT+dTsHgA81zI1Iz2bLVReBn0HVebZV/Vh7rLPDp/tYWMNahajhyWICRb67BPJqvQ8ENfDkuHNgZg7BuCwwU7ZDq8/xiXchKQjEdsaPOlwwyMk9EeEEIibH4dJgwUmI6Adpz24lJSjoa+trxcUjpcq6EfbpZ9yTBg6XXK5O1qNEJDqJiJzkIaaXZ5yQS8ntDA=
  template:
    metadata:
      name: github-token
      namespace: kyverno
