apiVersion: v2
name: envoy-ai-gateway
version: 1.0.0

dependencies:
  - name: ai-gateway-crds-helm
    version: v0.6.0
    repository: oci://docker.io/envoyproxy
  - name: ai-gateway-helm
    version: v0.6.0
    repository: oci://docker.io/envoyproxy
