ai-gateway-crds-helm: {}

ai-gateway-helm:

  extProc:
    logLevel: info
  controller:
    logLevel: info
    replicaCount: 1
    podSecurityContext: { }
    securityContext: { }
    mutatingWebhook:
      certManager:
        enable: true
    resources: { }

  envoyGateway:
    namespace: envoy-gateway
