apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eventbus-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      controller: eventbus-controller
      eventbus-name: default
