{{- if .Values.controller.extensions }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-sandbox-controller-extensions
  labels:
    {{- include "agent-sandbox.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: agent-sandbox-controller
  namespace: {{ include "agent-sandbox.namespace" . }}
roleRef:
  kind: ClusterRole
  name: agent-sandbox-controller-extensions
  apiGroup: rbac.authorization.k8s.io
{{- end }}
