apiVersion: v1
kind: Service
metadata:
  name: agent-sandbox-controller
  namespace: {{ include "agent-sandbox.namespace" . }}
  labels:
    {{- include "agent-sandbox.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "agent-sandbox.selectorLabels" . | nindent 4 }}
  ports:
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
