apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-sandbox-controller
  namespace: {{ include "agent-sandbox.namespace" . }}
  labels:
    {{- include "agent-sandbox.labels" . | nindent 4 }}
