apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhookServiceName }}
  namespace: {{ include "agent-sandbox.namespace" . }}
  labels:
    {{- include "agent-sandbox.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "agent-sandbox.selectorLabels" . | nindent 4 }}
  ports:
  - name: webhook
    port: 443
    targetPort: 9443
    protocol: TCP
