descheduler:
  kind: Deployment
  deschedulingInterval: 5m
  cmdOptions:
    dry-run: true
  resources:
    requests:
      cpu: 20m
      memory: 50Mi
    limits:
      cpu: null
      memory: 100Mi

  service:
    enabled: true

  serviceMonitor:
    enabled: true

  deschedulerPolicyAPIVersion: descheduler/v1alpha2
  deschedulerPolicy:
    maxNoOfPodsToEvictPerNode: 2
    maxNoOfPodsToEvictPerNamespace: 2
    maxNoOfPodsToEvictTotal: 5
    evictionFailureEventNotification: true
    metricsProviders:
      - source: KubernetesMetrics
    profiles:
      - name: default
        pluginConfig:
          - name: DefaultEvictor
            args:
              nodeFit: true
              minPodAge: 10m
              podProtections:
                extraEnabled:
                  - PodsWithPVC
                  - PodsWithoutPDB
          - name: RemovePodsHavingTooManyRestarts
            args:
              podRestartThreshold: 10
              includingInitContainers: true
          - name: RemoveFailedPods
            args:
              reasons:
                - Evicted
              excludeOwnerKinds:
                - Job
              minPodLifetimeSeconds: 3600
              includingInitContainers: true
          - name: RemoveDuplicates
          - name: LowNodeUtilization
            args:
              thresholds:
                cpu: 20
                memory: 20
                pods: 20
              targetThresholds:
                cpu: 50
                memory: 50
                pods: 50
              metricsUtilization:
                source: KubernetesMetrics
          - name: RemovePodsViolatingNodeAffinity
            args:
              nodeAffinityType:
                - requiredDuringSchedulingIgnoredDuringExecution
                - preferredDuringSchedulingIgnoredDuringExecution
          - name: RemovePodsViolatingInterPodAntiAffinity
          - name: RemovePodsViolatingTopologySpreadConstraint
            args:
              topologyBalanceNodeFit: true
              constraints:
                - DoNotSchedule
                - ScheduleAnyway
          - name: RemovePodsViolatingNodeTaints
            args:
              includePreferNoSchedule: true
              excludedTaints:
                - node.kubernetes.io/unschedulable
        plugins:
          deschedule:
            enabled:
              - RemovePodsHavingTooManyRestarts
              - RemoveFailedPods
              - RemovePodsViolatingInterPodAntiAffinity
              - RemovePodsViolatingNodeAffinity
              - RemovePodsViolatingNodeTaints
          balance:
            enabled:
              - RemoveDuplicates
              - LowNodeUtilization
              - RemovePodsViolatingTopologySpreadConstraint
