{{- range $route := .Values.proxiedRoutes }}
{{- if $route.auth }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $route.name }}-proxy-auth
spec:
  encryptedData:
    credential: {{ $route.auth.credentialSealed }}
  template:
    metadata:
      name: {{ $route.name }}-proxy-auth
---
{{- end }}
{{- end }}
