{{- range $route := .Values.proxiedRoutes }}
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ $route.name }}-proxy
  labels:
    kubernetes.io/service-name: {{ $route.name }}-proxy
ports:
  - name: http
    port: {{ $route.port }}
endpoints:
  - addresses:
      - {{ $route.ip }}
    conditions: {}
---
{{- end }}
