apiVersion: v2
name: argo-workflows
version: 1.0.12

dependencies:
  - name: argo-workflows
    version: 1.0.13
    repository: https://argoproj.github.io/argo-helm
  - name: gatus-monitor
    repository: file://../../../templates/gatus-monitor
    version: 1.0.0

