gha-runner-scale-set-controller:
  replicaCount: 2

  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

  metrics:
    controllerManagerAddr: ":8080"
    listenerAddr: ":8080"
    listenerEndpoint: "/metrics"

  flags:
    logLevel: warn
    logFormat: json
    terminatedRunnerPodGracePeriodSeconds: 10
    healthProbeBindAddress: ":8081"

gha-runner-scale-set:
  githubConfigUrl: https://github.com/FlorisFeddema
  githubConfigSecret: github-actions-runners-secret

  controllerServiceAccount:
    namespace: github-actions-runners
    name: github-actions-runners-gha-rs-controller
  
  maxRunners: 3
  minRunners: 1

  runnerScaleSetName: feddemadev-runners
  containerMode:
    type: dind
  
  template:
    spec:
      resources:
        requests:
          cpu: 2
          memory: 2Gi
        limits:
          cpu: 2
          memory: 2Gi
      runtimeClassName: kata
      containers:
        - name: runner