apiVersion: v1
kind: Service
metadata:
  name: kata-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kata-monitor
spec:
  selector:
    app.kubernetes.io/name: kata-monitor
  ports:
    - name: metrics
      port: 8090
      targetPort: metrics
      protocol: TCP