apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kata-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: kata-monitor
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kata-monitor
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitor.serviceMonitor.interval }}
      relabelings:
        - sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node