kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: default-tls-certificate
spec:
  secretName: default-tls-certificate
  dnsNames: {{ toYaml .Values.defaultTlsCertificate.domains | nindent 4 }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-dns
  revisionHistoryLimit: 1
  usages:
    - digital signature
    - key encipherment
