{{- range $name, $gateway := .Values.gateways }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-gateway-{{ $name }}
spec:
  telemetry:
    accessLog:
      settings:
        - type: Route
          sinks:
            - type: File
              file:
                path: /dev/stdout
        - type: Listener
          sinks:
            - type: File
              file:
                path: /dev/stdout
        - type: Upstream
          sinks:
            - type: File
              file:
                path: /dev/stdout
  shutdown:
    drainTimeout: 240s
  provider:
    type: Kubernetes
    kubernetes:
      envoyPDB:
{{ toYaml $gateway.pdb | nindent 8 }}
      envoyDeployment:
        patch:
          type: StrategicMerge
          value:
            spec:
              revisionHistoryLimit: 0
              template:
                spec:
                  # Run as nonroot
                  volumes:
                    - name: tmp
                      emptyDir: {}
                  containers:
                    - name: envoy
                      volumeMounts:
                        - name: tmp
                          mountPath: /tmp
                    - name: shutdown-manager
                      volumeMounts:
                        - name: tmp
                          mountPath: /tmp
        replicas: {{ $gateway.replicas }}
        container:
          resources:
            {{ toYaml $gateway.resources | nindent 12 }}
      envoyService:
        annotations:
          'io.cilium/lb-ipam-ips': {{ $gateway.serviceAddress }}
        externalTrafficPolicy: Local
        allocateLoadBalancerNodePorts: false
---
{{- end }}
