{{- range $name, $_ := .Values.gateways }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: envoy-gateway-{{ $name }}-podmonitor
spec:
  podMetricsEndpoints:
    - port: metrics
      scheme: http
      path: /stats/prometheus
  namespaceSelector:
    matchNames:
      - envoy-gateway
  selector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - proxy
      - key: app.kubernetes.io/managed-by
        operator: In
        values:
          - envoy-gateway
      - key: app.kubernetes.io/name
        operator: In
        values:
          - envoy
      - key: gateway.envoyproxy.io/owning-gateway-name
        operator: In
        values:
          - envoy-gateway-{{ $name }}
---
{{- end }}
