apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendLBPolicy
metadata:
  name: alertmanager-lb-policy
  namespace: prometheus
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: prometheus-alertmanager
  sessionPersistence:
    sessionName: "alertmanager-affinity"
    absoluteTimeout: "1h"
    idleTimeout: "10m"
    type: Cookie
    cookieConfig:
      lifetimeType: Session
