{{- if and .Values.argocdMcp.enabled .Values.argocdMcp.secret.apiTokenSealed -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.argocdMcp.secret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    ARGOCD_API_TOKEN: {{ .Values.argocdMcp.secret.apiTokenSealed }}
  template:
    metadata:
      name: {{ .Values.argocdMcp.secret.name }}
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
