{{- if and .Values.argocdMcp.enabled .Values.argocdMcp.bearerAuth.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-mcp-server-secret-init
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}
