---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore
  namespace: prometheus
spec:
  encryptedData:
    objstore.yml: AgCnl6i/ekmqe6e11ZYUTVEgSQmwmZ1Y6UAcG4M/QXrjI7Rh465dQl64sdxvMSbDdRWJYE27EZ6UbhvR2Zd2ZDkZH2k9PUkdbqi9BfLkiySfKTqcrh3kfK9e9S2aV9ddSatRnYuX3DiZaUWqt7DZTuz1vfXZUXQtqp6HPcawbGf1XWYSnK4HBsWHSMnVnETJa2Qw09kFoJwc4yg6umoJQ7QODn3VNIG2tMiPs5sVaXH7nAZbFW+wkCddF5M6sGrGoN2zjckudR9Bob2FGs7lhHCyXWjZEDfEqDyIEdTSG9bM14neee/GXJnn7KH6CAvZE63/XDFakmcnAjENrMHx9NfvZqmqauulr28GTaz1CsSx3Hw/hde3BI4RG6fV5YP1j6+/BWTSpU/bYxOoAftfNkmBhXCZfG1GtzvD5bmKRCvQLeQ4dsl+eXV9nyHGEqAC39ioR2yWKEzOFY1dHpq3WV4DGtrowulc9bZkOxaK+VbbydDnCC6Tim1dNSrMdYAkaCLGIufQ+3h7U0fShHlRYKKJZOI4SpoLad8Idmt/T6B6C4s9iVabzaoQ9EtJeDOrWKVbaVdPxLvW8xCVg9m4LB84toedX0d8ZF3X8C4zwTr2F7aHMlIVewsROapCo6aOwB7buxM4KylvH/59056buw9eEUN/uG+exqQhnRW11+KfhGiH2kLyJhf3be4WCU+yZJaK0d1XCxa3IujtUA1deoFIvZozfy7lX2vkWnmheY8P6HkTzzRRgmSWU9JLefVcHnoqCKWCflqU9uUQZNijqRpgS9KK2Ikpo7fJUlBare6ruK9MtsIpd6ixYtG3PzAOzc4l8XKV4MiNdOmFhFlKDrTVcXd6XTEH1v1dxjJCiCRJ5qpw02RZqw==
  template:
    metadata:
      name: thanos-objstore
      namespace: prometheus
