{{- if .Values.route.auth.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-mcp-server-secret-init
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
{{- end }}
