machine:
  type: worker
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  runtime.feddema.dev/kata: "true"
  topology.kubernetes.io/zone: hortek
  topology.kubernetes.io/region: salioca
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: factory.talos.dev/metal-installer/882fc2311afd7c635b793e27fb91c65825791df79dd505a6db58ba500968efab:v1.14.2
provisioning:
  diskSelector:
    match: disk.wwid == "naa.5002538e4089b4e1"
  wipe: false
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: hortek-0
auto: off
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp1s0f1
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp1s0f1
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp1s0f0
mtu: 9000
addresses:
  - address: 192.168.5.15/24
routes:
  - destination: 192.168.5.0/24
    gateway: 192.168.5.1
