machine:
  type: worker
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  runtime.feddema.dev/kata: "true"
  topology.kubernetes.io/zone: kashaylan
  topology.kubernetes.io/region: salioca
---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: factory.talos.dev/metal-installer/8b68daecde55a895bf457a225b4a0d1da86618f31e61b3cc2c704b85b10d70bd:v1.14.2
provisioning:
  diskSelector:
    match: disk.serial == "0x5edae82c"
  wipe: false
---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: kashaylan-0
auto: off
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: end0
---
apiVersion: v1alpha1
kind: LinkConfig
name: end0
