apiVersion: v1alpha1
kind: HostnameConfig
hostname: tasuq-0
auto: off
---
apiVersion: v1alpha1
kind: Layer2VIPConfig
name: 192.168.4.9
link: enp1s0
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: enp1s0
---
apiVersion: v1alpha1
kind: LinkConfig
name: enp1s0
