gatus-monitor:
  appName: argocd
  publicEndpoints:
    - name: argocd
  privateEndpoints:
    - name: argocd

argocdMcpBearerAuth:
  enabled: true
  secretInit:
    image:
      repository: alpine/kubectl
      tag: 1.35.3
    resources: {}

argocdMcp:
  enabled: true

  route:
    enabled: true
    hostnames:
      - argocd-mcp.feddema.dev
    parentRefs:
      - name: envoy-gateway-private
        namespace: envoy-gateway
        sectionName: web-https

  secret:
    name: argocd-mcp-server-credentials
    apiTokenSealed: "" # seal argocd account token for argocd-mcp user in argocd namespace

  image:
    repository: quay.io/argoprojlabs/mcp-for-argocd
    tag: v0.3.0
    pullPolicy: IfNotPresent

  server:
    baseURL: http://argocd-server.argocd
    port: 3000

  replicaCount: 1

  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi

argo-cd:
  nameOverride: argocd
  fullnameOverride: argocd
  global:
    revisionHistoryLimit: 0
    logging:
      format: json
      level: warn

  crds:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true

  configs:
    cm:
      create: false
      exec.enabled: true

    secret:
      createSecret: true

    params:
      server.insecure: true
      hydrator.enabled: "true"

    rbac:
      create: false

  controller:
    replicas: 1

    resources:
      limits:
        memory: 3Gi
      requests:
        cpu: 300m
        memory: 1500Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  dex:
    enabled: false

  redis:
    enabled: true

    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 30m
        memory: 50Mi

    exporter:
      enabled: false

  server:
    replicas: 1

    httproute:
      enabled: true
      hostnames:
        - argocd.feddema.dev
      parentRefs:
        - name: envoy-gateway-public
          namespace: envoy-gateway
          sectionName: web-https
        - name: envoy-gateway-private
          namespace: envoy-gateway
          sectionName: web-https
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          timeouts:
            request: 5m
            backendRequest: 5m


    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 150m
        memory: 150Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    configEnabled: false

    rbacConfigCreate: false

  repoServer:
    replicas: 1

    resources:
      limits:
        memory: 900Mi
      requests:
        cpu: 120m
        memory: 450Mi

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

  applicationSet:
    replicas: 0
    serviceAccount:
      create: false
      allowAnyNamespace: false
      
  notifications:
    enabled: false

  commitServer:
    enabled: false
