{
 "title": "Envoy Solarpanels",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Today",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(job) (envoy_production_watthours_today / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lifetime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kwh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by(job) (envoy_production_watthours_lifetime / 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(job) (envoy_production_watts_now)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by(job) (envoy_production_inverter_last_reported_watts)",
     "legendFormat": "Production"
    }
   ]
  },
  {
   "title": "Production per panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by(serialNumber) (envoy_production_inverter_last_reported_watts)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloud connection",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(job) (envoy_system_connected)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}