apiVersion: v2
name: falco
version: 1.0.82

dependencies:
  - name: falco
    version: 9.1.0
    repository: https://falcosecurity.github.io/charts
  - name: gatus-monitor
    repository: file://../../../templates/gatus-monitor
    version: 1.0.0
