gatus-monitor:
  appName: radarr
  publicEndpoints:
    - name: radarr
  privateEndpoints:
    - name: radarr

podSecurityContext:
  fsGroup: 5000
securityContext: {}

mediaPvcName: media-server-media

resources:
  limits:
    memory: 350Mi
  requests:
    cpu: 20m
    memory: 200Mi

image:
  registry: ghcr.io
  repository: linuxserver/radarr
  tag: 6.1.1

persistence:
  size: 1Gi
  labels:
    backup.velero.io/include: "true"

route:
  enabled: true
  hostnames:
    - radarr.feddema.dev
  parentRefs:
    - name: envoy-gateway-public
      namespace: envoy-gateway
      sectionName: web-https
    - name: envoy-gateway-private
      namespace: envoy-gateway
      sectionName: web-https
