gatus-monitor:
  appName: emqx
  publicEndpoints:
    - name: emqx
  privateEndpoints:
    - name: emqx

route:
  enabled: true
  hostnames:
    - emqx.feddema.dev
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway-public
      namespace: envoy-gateway
      sectionName: web-https
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-gateway-private
      namespace: envoy-gateway
      sectionName: web-https
  matches:
    - path:
        type: PathPrefix
        value: /

emqx-operator:
  revisionHistoryLimit: 0
  replicaCount: 1

  resources:
    limits:
      cpu: null
      memory: 250Mi
    requests:
      cpu: 20m
      memory: 100Mi
cluster:
  replicas: 3
  pdb:
    minAvailable: 2

  replicant:
    replicas: 0

  persistence:
    accessMode: ReadWriteOnce
    size: 500Mi

  image:
    repository: emqx/emqx
    tag: 5.8.9

  listener:
    service:
      enabled: true
      type: LoadBalancer
      hostname: mqtt.feddema.dev
      externalTrafficPolicy: Local

  certificate:
    domain: mqtt.feddema.dev
    issuer: letsencrypt-dns
