apiVersion: v1
kind: Service
metadata:
  name: argocd-mcp-server
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    app.kubernetes.io/name: argocd-mcp-server
