{
 "title": "PolicyReport Details",
 "tags": [ "Policy Reporter" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "policy",
    "label": "Policy",
    "query": "label_values(policy_report_result, policy)"
   },
   {
    "name": "category",
    "label": "Category",
    "query": "label_values(policy_report_result, category)"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "label_values(policy_report_result, severity)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(policy_report_result, namespace)"
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": "label_values(policy_report_result, kind)"
   }
  ]
 },
 "panels": [
  {
   "title": "Policy Pass Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\", status=\"pass\"} > 0) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Policy Fail Status",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\", status=\"fail\"} > 0) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Status Timeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\"} > 0) by (status, namespace)",
     "legendFormat": "{{ namespace }} {{ status }}"
    }
   ]
  },
  {
   "title": "Passed Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\", status=\"pass\"}) by (namespace,category,policy,rule,kind,name,severity,status)"
    }
   ]
  },
  {
   "title": "Failed Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\", status=\"fail\"}) by (namespace,category,policy,rule,kind,name,severity,status)"
    }
   ]
  }
 ]
}