apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: etcd-certificate-bootstrap
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
subjects:
  - kind: ServiceAccount
    name: etcd-certificate-bootstrap
    namespace: prometheus-etcd-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: etcd-certificate-bootstrap