apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: etcd-certificate-bootstrap
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups: [""]
    resources:
      - secrets
    resourceNames:
      - etcd-client-cert
    verbs:
      - get
      - update
      - patch