apiVersion: v1
kind: ServiceAccount
metadata:
  name: etcd-certificate-bootstrap
  namespace: prometheus-etcd-exporter
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded