apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: etcd-certificate-bootstrap-talos-secrets
  namespace: prometheus-etcd-exporter
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  roles:
    - os:admin