apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 192.168.4.1
---
apiVersion: v1alpha1
kind: TimeSyncConfig
ntp:
  servers:
    - europe.pool.ntp.org
---
apiVersion: v1alpha1
kind: KmsgLogConfig
name: remote-log
url: udp://10.102.209.253:12345/
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: registry.k8s.io
endpoints:
  - url: https://harbor.feddema.dev/v2/proxy-registry.k8s.io
    overridePath: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: ghcr.io
endpoints:
  - url: https://harbor.feddema.dev/v2/proxy-ghcr.io
    overridePath: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: mirror.gcr.io
endpoints:
  - url: https://harbor.feddema.dev/v2/proxy-mirror.gcr.io
    overridePath: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: docker.io
endpoints:
  - url: https://harbor.feddema.dev/v2/proxy-docker.io
    overridePath: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: public.ecr.aws
endpoints:
  - url: https://harbor.feddema.dev/v2/proxy-public.ecr.aws
    overridePath: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: quay.io
endpoints:
  - url: https://harbor.feddema.dev/v2/proxy-quay.io
    overridePath: true
---
apiVersion: v1alpha1
kind: RegistryMirrorConfig
name: reg.kyverno.io
endpoints:
  - url: https://harbor.feddema.dev/v2/proxy-reg.kyverno.io
    overridePath: true
