apiVersion: v1alpha1
kind: ResolverConfig
nameservers:
  - address: 192.168.4.1
---
apiVersion: v1alpha1
kind: TimeSyncConfig
ntp:
  servers:
    - europe.pool.ntp.org
---
apiVersion: v1alpha1
kind: KmsgLogConfig
name: remote-log
url: udp://10.102.209.253:12345/
