machine:
  certSANs:
    - 192.168.102.21

  logging:
    destinations:
      - endpoint: "udp://10.102.209.253:12345"
        format: "json_lines"

  features:
    diskQuotaSupport: true

---
apiVersion: v1alpha1
kind: KubeClusterConfig
clusterName: gerador
endpoint: https://gerador.feddema.dev:6443
---
apiVersion: v1alpha1
kind: DiscoveryServiceConfig
name: default
endpoint: https://discovery.talos.dev/
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
dnsDomain: cluster.local
podSubnets:
  - 10.244.0.0/16
serviceSubnets:
  - 10.96.0.0/12
---
apiVersion: v1alpha1
kind: KubeletConfig
clusterDNS:
  - 10.96.0.10
extraArgs:
  cloud-provider: external
  rotate-server-certificates: true
---
apiVersion: v1alpha1
kind: KubeNodeConfig
nodeIP:
  validSubnets:
    - 192.168.4.0/24
---
apiVersion: v1alpha1
kind: KubePrismConfig
port: 7445
---
apiVersion: v1alpha1
kind: ResolverConfig
hostDNS:
  enabled: false
  forwardKubeDNSToHost: false
---
apiVersion: v1alpha1
kind: SecurityProfileConfig
workloadIsolation: true