cluster:
  etcd:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
---
apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
$patch: delete
---
apiVersion: v1alpha1
kind: KubeCoreDNSConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
resources:
  requests:
    cpu: 700m
    memory: 7Gi
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
extraArgs:
  bind-address: 0.0.0.0
resources:
  requests:
    cpu: 50m
    memory: 300Mi
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
extraArgs:
  bind-address: 0.0.0.0
resources:
  requests:
    cpu: 50m
    memory: 100Mi
---
apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:reader
  - os:admin
allowedKubernetesNamespaces:
  - kube-system
  - tuppr
  - prometheus-etcd-exporter