apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
$patch: delete
---
apiVersion: v1alpha1
kind: KubeCoreDNSConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
resources:
  requests:
    cpu: 700m
    memory: 7Gi
---
apiVersion: v1alpha1
kind: KubeAuditPolicyConfig
configuration:
  apiVersion: audit.k8s.io/v1
  kind: Policy
  omitStages:
    - RequestReceived
  rules:
    - level: None
      nonResourceURLs:
        - /healthz*
        - /livez*
        - /readyz*
        - /metrics
    - level: None
      users:
        - system:kube-proxy
      verbs:
        - watch
    - level: None
      userGroups:
        - system:nodes
      verbs:
        - get
      resources:
        - group: ""
          resources:
            - nodes
            - nodes/status
    - level: Metadata
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
extraArgs:
  bind-address: 0.0.0.0
resources:
  requests:
    cpu: 50m
    memory: 300Mi
---
apiVersion: v1alpha1
kind: KubeSchedulerConfig
extraArgs:
  bind-address: 0.0.0.0
resources:
  requests:
    cpu: 50m
    memory: 100Mi
---
apiVersion: v1alpha1
kind: KubeTalosAPIAccessConfig
allowedRoles:
  - os:reader
  - os:admin
allowedKubernetesNamespaces:
  - kube-system
  - tuppr
  - prometheus-etcd-exporter
