apiVersion: v1
kind: Service
metadata:
  name: garage
  labels:
    {{- include "garage.labels" . | nindent 4 }}
spec:
  ports:
    - name: s3
      port: 3900
      targetPort: s3
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: garage-headless
  labels:
    {{- include "garage.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: 3901
      targetPort: rpc
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: garage-admin
  labels:
    {{- include "garage.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  ports:
    - name: metrics
      port: 3903
      targetPort: admin
  selector:
    {{- include "garage.selectorLabels" . | nindent 4 }}
