{
 "title": "Cluster status",
 "tags": [
  "custom",
  "cluster"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Restarts in last 15 minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "  increase(kube_pod_container_status_restarts_total{namespace=~\"$namespace\"}[15m])> 0",
     "legendFormat": "{{namespace}}/{{pod}} "
    }
   ]
  },
  {
   "title": "OOM in last 15 minutes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "  increase(container_oom_events_total{namespace=~\"$namespace\"}[15m])> 0",
     "legendFormat": "{{namespace}}/{{pod}} "
    }
   ]
  },
  {
   "title": "Node readiness",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "max by (node) (\n  kube_node_status_condition{condition=\"Ready\", status=\"true\"} * 1\n  or\n  kube_node_status_condition{condition=\"Ready\", status=\"false\"} * 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "kube_node_status_condition{\n  condition!=\"Ready\",\n  status=\"true\"\n} == 1",
     "legendFormat": "{{node}} - {{condition}}"
    }
   ]
  }
 ]
}