---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-credentials
  namespace: donetick
spec:
  encryptedData:
    client-secret: AgBTNmuD37YmqCr1Q16RoOYil7psz6kM6qva6pgIuuPjD0Qx9vQwJJ5KpmTvJiJxJ852ah/B8/1My+HtkJ/c3mf4oQB1b/zGH/kSNpS5VxvPm3Rzln3uLlbXxMRAYh1ZFRlts9snkk4KvqxrkZcNzWk5+0uz9tB3jwcL4oF8ywW4ONUXxTTB8UHPg3Vsr3AbbYJuj3MLE7L7CslqHnsZy4IkG6oElO7HbWqyMaRtSKW23dL5Ix1Uhia96Yn7YXF/Uac0wP2EHXxOHpgdutdtIkkgH95UOig79AYxpCYhjqT2n54BErO7/675gH7PdRBU3zQsCIklPJd5aAYmxFCDne1zP9PHtsWOB84V9H+vgak1HFRz+ACFpdIqDo2Sm8zabpNEQ61Wbe7NHKNIHy2BOIAenFvoza3FINOutVcCzYViLOcCszWDkcvTikT2Tvn/Gnh1INy5BhDqGd9+ZBp7zJDgRqX5hShSH0U+pQ65LlFsQazcrzHKWUKVsb0o0atMGXpzwJxXmT2SVy7ctmCUVcB1tIFY3W2nrSPQF9pdVea6CXEuO+KQ2bcJmQjwA3n+LTZoLSUvmEDmcJ1+C75zHJFv56rmg/kAEBpdOlmpk8nhf84oUfZwT4Gyue2KNwnMU6F2GtDw1bKv7/cgs23N4OmqYxZblAgY/j7yuaAzkoDKAmOfA9xE9039MWqw/gJ2zENPsRxb0Vvl/yDIsWklwdYvMn9X72Hd7JppuhQasarAShfBM6c4oq7UsY6UnOC58ERtbmXdi83t3+kEfbTZNztmSwaXQhHMoS3CXykHoMsMCMLODhShPeDE9jf9odjbKhuWZbgE/iRzwMDOj+H+8v0XTuu8kXhCSLIWTTMRNt0VTw==
  template:
    metadata:
      name: oidc-credentials
      namespace: donetick
