apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-mcp-server-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    ARGOCD_API_TOKEN: {{ .Values.apiTokenSealed }}
  template:
    metadata:
      name: argocd-mcp-server-credentials
      namespace: {{ .Release.Namespace }}
    type: Opaque
