{
 "title": "Pod Stats & Info",
 "description": "This is for insight on important Kubernetes app metrics.\r\nWhat recources is a Pod actually using and what are it's limits or requests and what part is each container consuming?\r\nAlso has graphs for networking, disks, restarts docker images etc",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU: $pod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$pod\",resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\"}[1m]))",
     "legendFormat": "CPU: $pod"
    }
   ]
  },
  {
   "title": "CPU: $container",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\",container=\"$container\",resource=\"cpu\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",container!=\"POD\",pod=\"$pod\",container=\"$container\",resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\",container=\"$container\"}[1m])) by (container)",
     "legendFormat": "Usage: {{ container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory: $pod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$pod\",resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\"})",
     "legendFormat": "MEM"
    },
    {}
   ]
  },
  {
   "title": "Memory: $container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "repeat": "container",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\",resource=\"memory\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\",resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\",container=\"$container\"}) by (container)",
     "legendFormat": "Usage: {{ container }}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Usage: $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 113 },
   "repeat": "container",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}[1m])) by (container,device)",
     "legendFormat": "Read {{ device }}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}[1m])) by (container,device)",
     "legendFormat": "Write {{ device }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network: $pod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "Network-Errors: $pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 159 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Receive-Errors%"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Receive-Dropped%"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Transmit-Errors%"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Transmit-Dropped%"
    }
   ]
  },
  {
   "title": "Restarts & Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Ready: $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 170 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Restarts: $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 202 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=\"$pod\", container=\"$container\"}[1m])",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 234 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", pod=\"$pod\"} > 0"
    }
   ]
  },
  {
   "title": "Waiting Reason",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 237 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\"} > 0"
    }
   ]
  },
  {
   "title": "Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 240 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod created",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_created{namespace=\"$namespace\",pod=\"$pod\"} * 1000",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Info: $pod",
   "type": "table-old",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 248 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  }
 ]
}