talosUpgrade:
  zones:
    - hortek
    - kashaylan
    - korris
    - tasuq

talos:
  image:
    repository: ghcr.io/siderolabs/installer
    tag: v1.13.9

kubernetes:
  image:
    repository: ghcr.io/siderolabs/kubelet
    tag: v1.36.3

tuppr:
  monitoring:
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
    dashboards:
      enabled: true

  resources: {}
  # limits:
  #   memory: 128Mi
  # requests:
  #   cpu: 10m
  #   memory: 64Mi

  controller:
    logLevel: info
