secretInit:
  image:
    repository: alpine/kubectl
    tag: 1.35.4

gatus-monitor:
  appName: nextcloud
  publicEndpoints:
    - name: nextcloud
  privateEndpoints:
    - name: nextcloud

route:
  enabled: true
  hostnames:
    - nextcloud.feddema.dev
  parentRefs:
    - name: envoy-gateway-public
      namespace: envoy-gateway
      sectionName: web-https
    - name: envoy-gateway-private
      namespace: envoy-gateway
      sectionName: web-https

database:
  clusterName: nextcloud-postgres
  size: 16Gi
  replicas: 2

nextcloud:
  replicaCount: 1

  httpRoute:
    enabled: true
    hostnames:
      - nextcloud.feddema.dev
    parentRefs:
      - name: envoy-gateway-public
        namespace: envoy-gateway
        sectionName: web-https
      - name: envoy-gateway-private
        namespace: envoy-gateway
        sectionName: web-https

  phpClientHttpsFix:
    enabled: true

  startupProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 50
    successThreshold: 1

  nextcloud:
    host: nextcloud.feddema.dev

    existingSecret:
      enabled: true
      secretName: nextcloud-credentials
      usernameKey: username
      passwordKey: password

  cronjob:
    enabled: true

  persistence:
    enabled: true
    size: 50Gi
    labels:
      backup.velero.io/include: "true"

  resources:
    limits:
      memory: 1600Mi
    requests:
      cpu: 300m
      memory: 800Mi

  internalDatabase:
    enabled: false

  externalDatabase:
    enabled: true
    type: postgresql
    host: nextcloud-postgres-rw
    database: app

    existingSecret:
      enabled: true
      secretName: nextcloud-credentials
      usernameKey: postgres-username
      passwordKey: postgres-password

  externalRedis:
    enabled: true
    host: nextcloud-redis-ha-haproxy
    port: 6379
    existingSecret:
      enabled: true
      secretName: nextcloud-redis-credentials
      passwordKey: redis-password

  metrics:
    enabled: true
    info:
      apps: true

  prometheus:
    serviceMonitor:
      enabled: true

  rbac:
    enabled: true
    serviceaccount:
      create: true
      name: nextcloud-serviceaccount

redis-ha:
  auth: true
  existingSecret: nextcloud-redis-credentials
  authKey: redis-password
  haproxy:
    enabled: true
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
        
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 40m
      memory: 64Mi

  sentinel:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 40m
        memory: 64Mi

  exporter:
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
