gatus-monitor:
  appName: sabnzbd
  publicEndpoints:
    - name: sabnzbd
  privateEndpoints:
    - name: sabnzbd

podSecurityContext:
  fsGroup: 5000
securityContext: {}

mediaPvcName: media-server-media

resources:
  requests:
    cpu: 100m
    memory: 1600Mi
  limits:
    memory: 3000Mi

image:
  registry: ghcr.io
  repository: linuxserver/sabnzbd
  tag: 5.0.1

persistence:
  size: 1Gi
  labels:
    backup.velero.io/include: "true"

route:
  enabled: true
  hostnames:
    - sabnzbd.feddema.dev
  parentRefs:
    - name: envoy-gateway-public
      namespace: envoy-gateway
      sectionName: web-https
    - name: envoy-gateway-private
      namespace: envoy-gateway
      sectionName: web-https
