apiVersion: v2
name: authentik
version: 1.0.64

dependencies:
  - name: authentik
    version: 2026.5.5
    repository: https://charts.goauthentik.io/
  - name: gatus-monitor
    repository: file://../../../templates/gatus-monitor
    version: 1.0.0
