apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-node-agent-config
  namespace: velero
data:
  velero-node-agent-config.json: |
    {
      "loadConcurrency": {
        "globalConfig": 4
      },
      "backupPVC": {
        "ceph-block-nvme-1": {
          "storageClass": "ceph-block-nvme-1",
          "readOnly": false
        },
        "ceph-block-nvme-2": {
          "storageClass": "ceph-block-nvme-2",
          "readOnly": false
        },
        "ceph-file-hdd": {
          "storageClass": "ceph-file-hdd",
          "readOnly": true,
          "spcNoRelabeling": true
        },
        "ceph-file-nvme-2": {
          "storageClass": "ceph-file-nvme-2",
          "readOnly": true,
          "spcNoRelabeling": true
        }
      }
    }
