mealie:
  persistence:
    labels:
      backup.velero.io/include: "true"

  ingress:
    enabled: false

  resources:
    limits:
      memory: 600Mi
    requests:
      cpu: 20m
      memory: 300Mi

  route:
    enabled: true
    hostnames:
      - mealie.feddema.dev
    parentRefs:
      - name: envoy-gateway-public
        namespace: envoy-gateway
        sectionName: web-https
      - name: envoy-gateway-private
        namespace: envoy-gateway
        sectionName: web-https

  config:
    baseUrl: mealie.feddema.dev
    allowSignups: false
    allowPasswordLogin: false
    oidc:
      enabled: true
      configurationUrl: https://authentik.feddema.dev/application/o/mealie/.well-known/openid-configuration
      clientId: PN9nh2X3931XH3BlVftMzBgECN3jheULqy5hP2E9
      clientSecretName: mealie-oidc-secret
      providerName: Authentik
      adminGroup: 'Admins'
