trivy-operator:
  operator:
    builtInTrivyServer: true
    clusterSbomCacheEnabled: true
    rbacAssessmentScannerEnabled: true
    infraAssessmentScannerEnabled: true
    clusterComplianceEnabled: true
    exposedSecretScannerEnabled: true
    configAuditScannerEnabled: false # We use Kyverno for this purpose
    revisionHistoryLimit: 0

  resources:
    limits:
      memory: 800Mi
    requests:
      cpu: 30m
      memory: 400Mi

  trivy:
    server:
      resources:
        limits:
          memory: 80Mi
        requests:
          cpu: 20m
          memory: 40Mi

  serviceMonitor:
    enabled: true

trivy-operator-polr-adapter:
  openreports:
    enabled: true
  adapters:
    vulnerabilityReports:
      enabled: true
    clusterVulnerabilityReports:
      enabled: true
    configAuditReports:
      enabled: true
    rbacAssessmentReports:
      enabled: true
    exposedSecretReports:
      enabled: true
    complianceReports:
      enabled: true
    infraAssessmentReports:
      enabled: true
    clusterInfraAssessmentReports:
      enabled: true
  resources:
    limits:
      memory: 120Mi
    requests:
      cpu: 20m
      memory: 60Mi
