{
 "title": "Crowdsec Insight",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(cs_info, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Up since",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{instance=\"$instance\"})*1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__interval])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Max FDs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total raw lines",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total{instance=\"$instance\"}[$__interval]) or up * 0) + sum(increase(cs_cloudwatch_stream_hits_total{instance=\"$instance\"}[$__interval]) or up * 0) + sum(increase(cs_journalctlsource_hits_total{instance=\"$instance\"}[$__interval]) or up * 0) + sum(increase(cs_syslogsource_hits_total{instance=\"$instance\"}[$__interval]) or up * 0)"
    }
   ]
  },
  {
   "title": "Total parsed lines",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ok_total{instance=\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Overflows",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total{instance=\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Process Open FDs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total unparsed lines",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ko_total{instance=\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Top scenarios",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total{instance=\"$instance\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}