{
 "title": "KeyCloak X MicroProfile Metrics",
 "description": "Visualize all KeyCloak X Metrics",
 "tags": [
  "keycloak x",
  "quarkus",
  "java"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(base_thread_count, env)"
    }
   },
   {
    "name": "job",
    "label": "Source of metrics",
    "query": {
     "query": "label_values(base_thread_count{env=\"$env\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "Host",
    "query": {
     "query": "label_values(base_thread_count{env=\"$env\",job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "KeyCloak X Base Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Available Processors",
   "type": "stat",
   "description": "Displays the number of processors available to the Java virtual machine. This value may change during a particular invocation of the virtual machine.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_cpu_availableProcessors{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Process CPU load",
   "type": "stat",
   "description": "Displays  the \"recent cpu usage\" for the Java Virtual Machine process. This value is a double in the [0.0,1.0] interval. A value of 0.0 means that none of the CPUs were running threads from the JVM process during the recent period of time observed, while a value of 1.0 means that all CPUs were actively running threads from the JVM 100% of the time during the recent period being observed. Threads from the JVM include the application threads as well as the JVM internal threads. All values betweens 0.0 and 1.0 are possible depending of the activities going on in the JVM process and the whole system. If the Java Virtual Machine recent CPU usage is not available, the method returns a negative value.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad_percent{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "System Load Average",
   "type": "stat",
   "description": "Displays the system load average for the last minute. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platforms where it is expensive to implement this method.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Used Heap Memory",
   "type": "timeseries",
   "description": "Displays the amount of used heap memory in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Committed Heap Memory",
   "type": "timeseries",
   "description": "Displays the amount of memory in bytes that is committed for the Java virtual machine to use. This amount of memory is guaranteed for the Java virtual machine to use.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_committedHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Max Heap Memory",
   "type": "timeseries",
   "description": "Displays the maximum amount of heap memory in bytes that can be used for memory management. This attribute displays -1 if the maximum heap memory size is undefined. This amount of memory is not guaranteed to be available for memory management if it is greater than the amount of committed memory. The Java virtual machine may fail to allocate memory even if the amount of used memory does not exceed this maximum size.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "base_memory_maxHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Total Loaded Class Count",
   "type": "timeseries",
   "description": "Displays the total number of classes that have been loaded since the Java virtual machine has started execution.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Total Unloaded Class Count",
   "type": "timeseries",
   "description": "Displays the total number of classes unloaded since the Java virtual machine has started execution.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_unloadedClasses_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "timeseries",
   "description": "Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_gc_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} name={{name}}"
    }
   ]
  },
  {
   "title": "JVM Uptime",
   "type": "timeseries",
   "description": "Displays the time from the start of the Java virtual machine in milliseconds.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Current Loaded Class Count",
   "type": "timeseries",
   "description": "Displays the number of classes that are currently loaded in the Java virtual machine.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "stat",
   "description": "Displays the current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 13 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_thread_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Daemon Thread Count",
   "type": "stat",
   "description": "Displays the current number of live daemon threads.",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 13 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_thread_daemon_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Peak Thread Count",
   "type": "stat",
   "description": "Displays the peak live thread count since the Java virtual machine started or peak was reset. This includes daemon and non-daemon threads.",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 13 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_thread_max_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "KeyCloak X Vendor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System CPU load",
   "type": "stat",
   "description": "Displays the \"recent cpu usage\" for the whole system. This value is a double in the [0.0,1.0] interval. A value of 0.0 means that all CPUs were idle during the recent period of time observed, while a value of 1.0 means that all CPUs were actively running 100% of the time during the recent period being observed. All values betweens 0.0 and 1.0 are possible depending of the activities going on in the system. If the system recent cpu usage is not available, the method returns a negative value.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "format": "percent",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cpu_systemCpuLoad_percent{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Process CPU time",
   "type": "stat",
   "description": "Displays the CPU time used by the process on which the Java virtual machine is running in nanoseconds. The returned value is of nanoseconds precision but not necessarily nanoseconds accuracy. This method returns -1 if the the platform does not support this operation.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_cpu_processCpuTime_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Used Non Heap Memory",
   "type": "timeseries",
   "description": "Displays the amount of used non-heap memory in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_usedNonHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Max Non Heap Memory",
   "type": "timeseries",
   "description": "Displays the maximum amount of used non-heap memory in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_maxNonHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Committed Non Heap Memory",
   "type": "timeseries",
   "description": "Displays the amount of non heap memory in bytes that is committed for the Java virtual machine to use.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_committedNonHeap_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Free physical memory size",
   "type": "timeseries",
   "description": "Displays the amount of free physical memory in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_freePhysicalSize_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Free swap size",
   "type": "timeseries",
   "description": "Displays the amount of free swap space in bytes.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memory_freeSwapSize_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Peak usage of the memory pool denoted by the 'name' tag",
   "type": "timeseries",
   "description": "Peak usage of the memory pool denoted by the 'name' tag",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_max_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} name={{name}}"
    }
   ]
  },
  {
   "title": "Current usage of the memory pool denoted by the 'name' tag",
   "type": "timeseries",
   "description": "Current usage of the memory pool denoted by the 'name' tag",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_bytes{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} name={{name}}"
    }
   ]
  },
  {
   "title": "Number of times an acquire operation succeeded",
   "type": "timeseries",
   "description": "Number of times an acquire operation succeeded.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_agroal_acquire_count_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Number active of connections",
   "type": "stat",
   "description": "Number active of connections.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_active_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Maximum number of connections active simultaneously",
   "type": "stat",
   "description": "Maximum number of connections active simultaneously.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_max_used_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Number of idle connections in the pool, available to be acquired",
   "type": "stat",
   "description": "Number of idle connections in the pool, available to be acquired.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_available_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Maximum time an application waited to acquire a connection",
   "type": "stat",
   "description": "Maximum time an application waited to acquire a connection.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_blocking_time_max_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Number of connections removed from the pool, not counting invalid / idle",
   "type": "timeseries",
   "description": "Number of connections removed from the pool, not counting invalid / idle.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_agroal_flush_count_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Number of times a leak was detected",
   "type": "timeseries",
   "description": "Number of times a leak was detected.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_agroal_leak_detection_count_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Number of created connections",
   "type": "timeseries",
   "description": "Number of created connections.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_agroal_creation_count_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Number of destroyed connections",
   "type": "timeseries",
   "description": "Number of destroyed connections.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_agroal_destroy_count_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Number of connections removed from the pool for being idle",
   "type": "timeseries",
   "description": "Number of connections removed from the pool for being idle.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_agroal_reap_count_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Number of connections removed from the pool for being invalid",
   "type": "timeseries",
   "description": "Number of connections removed from the pool for being invalid.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_agroal_invalid_count_total{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Average time for a connection to be created",
   "type": "stat",
   "description": "Average time for a connection to be created.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 50 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_creation_time_average_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Average time an application waited to acquire a connection",
   "type": "stat",
   "description": "Average time an application waited to acquire a connection.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 50 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_blocking_time_average_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Total time applications waited to acquire a connection",
   "type": "stat",
   "description": "Total time applications waited to acquire a connection.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 50 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_blocking_time_total_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Maximum time for a connection to be created",
   "type": "stat",
   "description": "Maximum time for a connection to be created.",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 50 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_creation_time_max_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Total time waiting for a connections to be created",
   "type": "stat",
   "description": "Total time waiting for a connections to be created.",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 50 },
   "format": "s",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_creation_time_total_seconds{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  },
  {
   "title": "Approximate number of threads blocked, waiting to acquire a connection",
   "type": "stat",
   "description": "Approximate number of threads blocked, waiting to acquire a connection.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 50 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vendor_agroal_awaiting_count{env=\"$env\",job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{job}}/{{instance}} "
    }
   ]
  }
 ]
}