{
 "title": "OOM and restarts",
 "description": "Contains panels that show:\r\n1. restarts per pod\r\n2. oom killed processes in the node\r\n3. pods that got oom killed",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_status_phase{job=\"kube-state-metrics\", cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Restarts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "delta(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods with OOM killed containers by last termination reason",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "uniqueValues" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\", namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "OOM killed processes per node delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "delta(node_vmstat_oom_kill[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}