{
 "title": "Smartmeter gateway",
 "tags": [
  "Energy",
  "Home",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Power usage over time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(job) (max by(tariff, job) (increase(smartmeter_gateway_power_consumed_total[$__range])))) - (sum by(job) (max by(tariff, job) (increase(smartmeter_gateway_power_produced_total[$__range]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas usage over time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (increase(smartmeter_gateway_gas_consumed[$__range]))"
    }
   ]
  },
  {
   "title": "Nett power usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max by(job) (smartmeter_gateway_power_consumed_nett)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}