apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-apikey
  namespace: grafana
spec:
  encryptedData:
    key: AgCiQiJkPt9lnPpf/GxQeHZCtAJYWuoLzEZ06RGf+tUsv+7VK1tYoxsXeI14+HdMz8mW5sFboL3b3437dJxPanB+F4NMar/wltz85aYjL3L42Ob3UYRoNuLjAzU8PAljDsRATvJUgBIb7cwTYHAxAMgQ18uVTpuHudBgmaMG4jtytlnmXtV766p3UqNmOSGqQFvmLxvJYau6oYRsyDwv2P1dpkewM/xCiDSuGFza5s1bWwPAqBfft5TfWIPOBmuf27z7miOWEKjp4//adoOvUDMHxt83oauTFWy9WRvEX62nVb2y737ZfiC5N5SPUd/TWNCPdC0EcSfIbAZENE4KxQDRSlUVttBRPwhijGwmavVgR9GgriU1xipkq0nZ+vlzPN9ncUwTQ8tA8Ob/9XnUnIYps3iFxLYlSBytI9pPTjFqD8FrtT516+TNaUBQkvt/turjWdRYkHkdIiwIEqLUC5Ax9/eQJ/LWgyjKhe1nfJR6e+VV2OihuDnWeYucyWloIt99VrA4aw7DZaQ4Iv+gQxAB2yTl3dh2Kj7zO2vrRTEFEGrkuWpXzNppIG/skjRxR8qoa4OZ8h6XxAm5HMo0ONPnbl3PEa/zL9GoISp9f89vKxYRZRwSHyPpKk6dxqp1Wiyb59qQKGt6pqL0pr54dhRtc6Yvq+pWErx46zLH5L7zGsx2u3AX0eP34uErF9xdc7uQJtQvLxlGdBcBOiyjkkWskJXsB7LPIC04KLupYPDy8KG6qsfbIDYVfce2jms/
  template:
    metadata:
      name: mcp-apikey
      namespace: grafana
    type: Opaque
