apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: gerador
spec:
  kubernetes:
    version: {{ .Values.kubernetes.image.tag }}
  healthChecks:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
