cert-manager:
  crds:
    enabled: true
    keep: true

  global:
    logLevel: 1
    revisionHistoryLimit: 0
    leaderElection:
      namespace: cert-manager

  resources:
    limits:
      memory: 150Mi
    requests:
      cpu: 20m
      memory: 60Mi

  webhook:
    resources:
      limits:
        memory: 75Mi
      requests:
        cpu: 20m
        memory: 25Mi

  cainjector:
    resources:
      limits:
        memory: 300Mi
      requests:
        cpu: 20m
        memory: 150Mi

  prometheus:
    enabled: true
    servicemonitor:
      enabled: true

  enableCertificateOwnerRef: true
  dns01RecursiveNameservers: 1.1.1.1:53,8.8.8.8:53
  extraArgs:
    - --enable-gateway-api

trust-manager:
  revisionHistoryLimit: 0
  crds:
    enabled: true
    keep: false

  resources:
    limits:
      memory: 60Mi
    requests:
      cpu: 20m
      memory: 30Mi

  app:
    metrics:
      service:
        enabled: true
        servicemonitor:
          enabled: true
