gatus-monitor:
  appName: cyberchef
  publicEndpoints:
    - name: cyberchef
    - name: tools
  privateEndpoints:
    - name: cyberchef
    - name: tools

cyberchef:
  ingress:
    enabled: false

  resources:
    limits:
      memory: 64Mi
    requests:
      cpu: 20m
      memory: 32Mi

  route:
    enabled: true
    hostnames:
      - cyberchef.feddema.dev
      - tools.feddema.dev
    parentRefs:
      - name: envoy-gateway-public
        namespace: envoy-gateway
        sectionName: web-https
      - name: envoy-gateway-private
        namespace: envoy-gateway
        sectionName: web-https
