cloudnative-pg:
  monitoring:
    podMonitorEnabled: true
    grafanaDashboard:
      create: true

  resources:
     limits:
       memory: 160Mi
     requests:
       cpu: 20m
       memory: 80Mi

plugin-barman-cloud:
  fullnameOverride: cloudnative-pg-plugin-barman-cloud
